# GS Week 15 part 2: watch-fors, pre-work, run sheet, blocks 7-8, tail.
import io, sys, re
f = 'docs/getting-started/week-15-commissioning.md'
s = io.open(f, encoding='utf-8').read()
fail = 0
def sub(old, new, label=''):
    global s, fail
    n = s.count(old)
    if n != 1:
        print(f'!! count={n}: {(label or old)[:64]}'); fail += 1; return
    s = s.replace(old, new)

sub('*The exit gate as a witnessed rite — the seniors leave having begun, not finished*',
    '*The exit gate as a witnessed rite — the cohort leaves having begun, not finished*')
sub("- The senior who freezes on the final rep. This is the one contingency to have fully decided in advance, and the team already has: **the gate is fluency across the arc, not perfection tonight.** A senior who has opened the container eight Tuesdays since October passed the gate weeks ago; tonight is the witness of it, not the exam. A stumble is not a fail. The recovery script is in Block 2. Never let a stumble hang in silence; never let it become the story of the night.",
    "- The member who freezes on the final rep. This is the one contingency to have fully decided in advance, and the team already has: **the gate is fluency across the arc, not perfection tonight.** A member who has opened the container eight evenings this year passed the gate weeks ago; tonight is the witness of it, not the exam. A stumble is not a fail. The recovery script is in Block 2. Never let a stumble hang in silence; never let it become the story of the night.")
sub("- The cohort treating this as the seniors' graduation *out* of the group. Name it from the front, early: they are not leaving. They are taking a place *in* the body — the serving place. The exit gate opens inward.",
    "- The room treating this as the cohort's graduation *out* of something. Name it from the front, early: nobody is leaving. The team is taking its place *in* the body — the serving place. The exit gate opens inward.")
sub("- Parents' pride overwhelming the teen. This is a good problem. A father who chokes up watching his daughter open the container from memory is the night working. Give it its moment; do not manage it away. But keep the rite moving — the pride gets its fullest expression in the blessing block, where it belongs.",
    "- A household's pride overwhelming the moment. This is a good problem. A wife who chokes up watching her husband open the container from memory is the night working. Give it its moment; do not manage it away. But keep the rite moving — the pride gets its fullest expression in the blessing block, where it belongs.")
sub("- Any senior whose sign-off did not confirm. This must have been handled privately, in Week 13's week, in the discernment conversation between parent and Lead Companion — **never discovered tonight.** If it happened: that senior is honored tonight, by name, for what they led across the series, and their commissioning waits for the next cycle with a clear, hopeful path. The contingency script is in Block 6. If the team walks into Week 15 without this settled, stop and settle it before the session — even at the cost of a delay.",
    "- Any member whose discernment landed on a different role. This must have been handled privately, in Week 13's week, in the discernment conversation between the covering and the convening leader — **never discovered tonight.** If it happened: that member is honored tonight, by name, for what they carried across the year, and their role in the family year is named with full dignity. The contingency script is in Block 5. If the team walks into Week 15 without this settled, stop and settle it before the session — even at the cost of a delay.")
sub("- The younger teens watching with hunger. Some junior teens will watch tonight and want this. That is not a risk — that is the pipeline forming. But do not promise anything from the front; note the names and bring them to the debrief.",
    "- The guests watching with hunger. Some household members and friends will watch tonight and want this. That is not a risk — that is the next cohort forming. But do not promise anything from the front; note the names and bring them to the debrief.")
sub("**Week 15 is low-risk for acute crisis. The standard protocols remain in force — Crisis Quick-Reference Card in every Companion pocket, pastoral / clinical backup on call, Section 6 unchanged. The one real risk tonight is not crisis but weight: the emotional weight of public blessing on teens who rarely receive it.**",
    "**Week 15 is low-risk for acute crisis. The standard protocols remain in force — Crisis Quick-Reference Card in every Companion pocket, pastoral / clinical backup on call, the safeguarding frame unchanged. The one real risk tonight is not crisis but weight: the emotional weight of public blessing on adults who rarely receive it.**")
sub("**If a new FC1 is overwhelmed during their blessing — tears, shaking, unable to stand still under the words.** This is the session working, not failing. Do not rush, do not rescue, do not make it smaller. Give them room. A hand on the shoulder from their parent; the room holds; the blessing continues when they can bear it. Some of these teens have never once stood in a room full of adults saying true, specific, good things about them. Let the weight land.",
    "**If a new Companion is overwhelmed during their blessing — tears, shaking, unable to stand still under the words.** This is the session working, not failing. Do not rush, do not rescue, do not make it smaller. Give them room. A hand on the shoulder from their household; the room holds; the blessing continues when they can bear it. Some of these leaders have never once stood in a room full of people saying true, specific, good things about them — decades of giving blessings is not the same as receiving one. Let the weight land.")
sub("**If anything heavier surfaces — a disclosure, a family conflict, anything from the Section 6 list.** Standard protocol. Two-adult rule. Step aside, do not interpret in the room, pastoral / clinical backup. The rite can pause and resume; a teen in crisis outranks the calendar.",
    "**If anything heavier surfaces — a disclosure, a household conflict, anything on the safeguarding list.** Standard protocol. Two Companions. Step aside, do not interpret in the room, pastoral / clinical backup. The rite can pause and resume; a person in crisis outranks the calendar.")
sub("Across fifteen weeks, a handful of senior teens did something the pilot discovered almost by accident: they led. They took the opening and closing container week after week from Week 5 on. They led the second runnings — Telling Your Story II, PROAPT II, the Garden walk-through. They taught the Rhythm and the two mercy cards in Week 13. They received feedback in front of their peers and came back the next Tuesday and led again. And when they led, the room leaned in like nothing else made it lean in.",
    "Across fifteen weeks, the members of this cohort did the thing the leadership-first challenge asked: they led each other. They took the opening and closing container week after week. They led the second runnings — Telling Your Story II, PROAPT II, the Garden walk-through. They taught the Rhythm and the cards in Week 13. They received feedback in front of their peers and came back the next week and led again. And when one of their own led, the room leaned in like nothing else made it lean in.")
sub("Tonight that accidental discovery becomes a deliberate act. The Companions-in-Formation are commissioned as FC1 — the first stable level of Formation Companion. The handbook's conviction governs the design: this is an exit gate, not a ceremony. A ceremony looks backward and applauds. A gate opens onto something. The four movements of tonight's rite are the gate's four hinges: the competency demonstrated (the final rep), the boundary made public (the three rules), the net confirmed (the covering), and the road entered (the commissioning, with the first Lab of the serving cycle on the calendar before anyone touches a coat).",
    "Tonight that year becomes a deliberate act. The cohort is commissioned as the host church's Formation Companion team. The conviction governs the design: this is an exit gate, not a ceremony. A ceremony looks backward and applauds. A gate opens onto something. The four movements of tonight's rite are the gate's four hinges: the competency demonstrated (the final rep), the boundary made public (the three rules), the net confirmed (the covering), and the road entered (the commissioning, with the family year's first date on the calendar before anyone touches a coat).")
sub("In the CCA year this night lands in January, at the opening of the spring term. That is not an accident of scheduling; it is the design breathing. The new FC1s do not walk out of this room into a summer of forgetting. They walk out into a full semester of serving — the Leader Lab rhythm, the next cohort forming, real reps ahead. The exit is an entrance. The calendar is the proof.",
    "Wherever the host church's calendar puts this night, the design breathes the same way: the new Companions do not walk out of this room into a season of forgetting. They walk out into the family year — the permission conversations, the planning rhythm, real families ahead. The exit is an entrance. The calendar is the proof.")
sub("- Weeks 5–14: every container a senior opened or closed built toward tonight's final rep. Container fluency is FC1's spine competency; it was formed by steady, low-risk repetition across the arc, which is exactly why tonight's demonstration is a gate with real dignity and not a pop quiz.",
    "- The whole year: every container a member opened or closed built toward tonight's final rep. Container fluency is a Companion's spine competency; it was formed by steady, low-risk repetition across the arc, which is exactly why tonight's demonstration is a gate with real dignity and not a pop quiz.")
sub("- The second runnings (Weeks 4, 8, 10) and Week 13: the marquee slots each senior led, which the blessings tonight will name specifically.",
    "- The second runnings (Weeks 4, 8, 10) and Week 13: the marquee slots the rotation leaders led, which the blessings tonight will name specifically.")
sub("- Leader Lab 1–6 (run alongside the series): the covering conversation happened in Lab 4; the mock full session and the Lab's own commissioning prayer happened in Lab 6. Tonight is the public form of what Lab 6 did privately.",
    "- The coaching alongside the series: each rotation leader's covering conversation happened in their pre-lead coaching. Tonight is the public form of what those conversations did privately.")
sub("- Leader Lab 3: the seniors were trained on the Three Vital Signs — Costly Telling, Response to Load, the Sought Stray. The charge tonight hands them that lens for keeps.",
    "- The year's observation: the cohort watched itself by the Three Vital Signs — Costly Telling, Response to Load, the Sought Stray. The charge tonight hands them that lens for keeps, turned now toward the families they will serve.")
sub("- Week 13's week: the discernment conversation — parent and Lead Companion, both agreeing the teen is ready. Confirmed before tonight, never discovered tonight.",
    "- Week 13's week: the discernment conversation — the covering and the convening leader, reading the year together. Confirmed before tonight, never discovered tonight.")
sub("All four. Self: the seniors' own formation is real and named — you cannot lead someone where you have not been. Others: the community witnesses, and the feedback loop that formed these leaders was communal from the start. God: the calling is confirmed the Acts 13 way — the community discerns, prays, lays on words, and sends. Mission: the serving cycle begins, calendared, before the room empties.",
    "All four. Self: the cohort's own formation is real and named — you cannot lead someone where you have not been. Others: the community witnesses, and the feedback loop that formed these leaders was communal from the start. God: the calling is confirmed the Acts 13 way — the community discerns, prays, lays on words, and sends. Mission: the family year begins, calendared, before the room empties.")
sub("Each Companion writes, this week, a specific witnessed blessing for each Companion-in-Formation being commissioned — one to three sentences per senior, drawn from what that Companion actually saw them lead across the fifteen weeks. Not \"you did great.\" What, specifically. The Tuesday she re-established the container when the junior circle got loud. The way he handed the heavy moment to the adult in Week 10 without hesitation and without drama — the rule working in the wild. Write it down; you will speak it in Block 6.",
    "Each member writes, this week, a specific witnessed blessing for the two members they are assigned — one to three sentences each, drawn from what they actually saw them carry across the year. Not \"you did great.\" What, specifically. The night she re-established the container when the circle got loud. The way he handed the heavy moment across in Week 10 without hesitation and without drama — the rule working in the wild. Write it down; you will speak it in Block 6.")
sub("1. Walk the run sheet. Assign the final-rep slots: who opens, who closes, who speaks which container condition (see Block 2 for the division). Tell each senior their slot this week — rehearsed dignity, not ambush.",
    "1. Walk the run sheet. Assign the final-rep slots: who opens, who closes, who speaks which container condition (see Block 2 for the division). Tell each member their slot this week — rehearsed dignity, not ambush.")
sub("2. Confirm every sign-off. For each Companion-in-Formation: has the parent confirmed? Has the Lead Companion confirmed? Any senior not confirmed is contacted privately this week — the honoring-tonight, commissioning-next-cycle conversation happens before Tuesday, with hope in it, never in the room.",
    "2. Confirm the discernment. Has the covering read the year and said yes? Any member whose discernment landed on a different role is spoken with privately this week — the honoring-tonight, role-named-with-dignity conversation happens before the night, with hope in it, never in the room.")
sub("3. Set the date. The first Leader Lab of the spring serving cycle — an actual date, on the actual calendar, before Tuesday. The Lead Companion announces it in Block 7. Do not walk in without it.",
    "3. Set the date. The family year's first step — the opening night, or the first permission conversations week — an actual date, on the actual calendar, before the night. The convening leader announces it in Block 7. Do not walk in without it.")
sub("4. Blessing review. Each Companion reads their blessings for the seniors aloud to the team. Trim anything generic. The Week 14 discipline holds: specific, witnessed, brief.",
    "4. Blessing review. Each member reads their blessings aloud to the team. Trim anything generic. The Week 14 discipline holds: specific, witnessed, brief.")
sub("5. Decide the grace protocol out loud, as a team, even though it is already written: the gate is fluency-over-the-arc, not perfection tonight. Every Companion should be able to say it in their sleep, because if a senior freezes, the recovery must be instant and unanimous.",
    "5. Decide the grace protocol out loud, as a team, even though it is already written: the gate is fluency-over-the-arc, not perfection tonight. Everyone should be able to say it in their sleep, because if a member freezes, the recovery must be instant and unanimous.")
sub("6. Pray for each senior by name.", "6. Pray for each member by name.")
sub("## **Family and senior pre-work — sent early in the week**",
    "## **Household and member pre-work — sent early in the week**")
sub('Email to all families: *"Tuesday is Week 15, our final gathering — Commissioning the Companions. This is the night our Companions-in-Formation, the seniors who led us this year, are commissioned as Formation Companions, Level One. The whole cohort and all families are wanted in the room: a commissioning needs witnesses, and they earned ours. 6:30 start, 8:00 close. Light dessert after."*',
    'Email to all households: *"This week is Week 15, our final gathering — the Commissioning. This is the night the church commissions this cohort as its Formation Companion team, and sends them toward the family year. Every household is wanted in the room: a commissioning needs witnesses, and they earned ours. 6:30 start, 8:00 close. Light dessert after."*')
sub('Email to each Companion-in-Formation (individually): their final-rep slot (open, close, or which container condition they will speak from memory, with a story of holding it); a reminder that the covering movement will ask them to name their person aloud — decide the name before Tuesday (it was chosen in Lab 4; confirm it still holds); and one line of steel and warmth: *"You have done this every week since the fall. Tuesday you do it in front of everyone who loves you. Same container. More witnesses."*',
    'Email to each member (individually): their final-rep slot (open, close, or which container condition they will speak from memory, with a story of holding it); a reminder that the covering movement will ask them to name their person aloud — decide the name before the night and confirm it still holds; and one line of steel and warmth: *"You have done this every week for a year. This week you do it in front of everyone who loves you. Same container. More witnesses."*')
sub("1. Print Handout H15.1 — the FC1 Commissioning Card, one per senior, cardstock.",
    "1. Print Handout H15.1 — the Companion Commissioning Card, one per member, cardstock.")
sub("2. Print Handout H15.2 — the Limits Card (Appendix I reprint), one per senior, cardstock, laminated if possible.",
    "2. Print Handout H15.2 — the Limits Card (Appendix I reprint), one per member, cardstock, laminated if possible.")
sub("3. Print Handout H15.3 — the keepsake sheet, one per senior, heavy paper. Pens on the signing table.",
    "3. Print Handout H15.3 — the keepsake sheet, one per member, heavy paper. Pens on the signing table.")
sub("4. Confirm the first Leader Lab date one final time with the adult who runs the Lab.",
    "4. Confirm the family year's first date one final time with the covering.")
sub("- Handouts H15.1 and H15.2 for each senior; H15.3 laid out on the side table with pens.",
    "- Handouts H15.1 and H15.2 for each member; H15.3 laid out on the side table with pens.")
sub("- The Lab date, written large on a card the Lead Companion holds up in Block 7. Yes, physically. The calendar is the proof; let the room see it.",
    "- The family year's date, written large on a card the convening leader holds up in Block 7. Yes, physically. The calendar is the proof; let the room see it.")
sub("| Early in week | Emails to families and to each senior with their final-rep slot. | Lead Comp |",
    "| Early in week | Emails to households and to each member with their final-rep slot. | Lead Comp |")
sub("| 3–5 days before | Team meeting: run sheet, sign-off confirmation, Lab date set, blessing review, grace protocol. | All Companions |",
    "| 3–5 days before | Team meeting: run sheet, discernment confirmation, family-year date set, blessing review, grace protocol. | All Companions |")
sub("| By Friday | Any unconfirmed sign-off handled privately, with hope, never left for Tuesday. | Lead Comp + parent |",
    "| By Friday | Any different-role discernment handled privately, with hope, never left for the night. | Lead Comp + covering |")
sub("| T-60 min | Team gathers. Room setup. Handouts placed. Final prayer for each senior by name. | All Companions |",
    "| T-60 min | Team gathers. Room setup. Handouts placed. Final prayer for each member by name. | All Companions |")
sub("| 6:30 | Session opens. | Lead Comp — then the seniors |",
    "| 6:30 | Session opens. | Lead Comp — then the cohort |")
sub("| 6:40–6:55 | Block 2: The final rep — the container opened | Movement 1 | The seniors | One senior opens from memory; the others each speak a condition from memory with a story. No scripts, no cards. |",
    "| 6:40–6:55 | Block 2: The final rep — the container opened | Movement 1 | The cohort | One member opens from memory; the rotation leaders each speak a condition from memory with a story. No scripts, no cards. |")
sub("| 7:05–7:15 | Block 4: The three rules read aloud | Movement 2 | Lead Comp + seniors | Verbatim from the handbook, to the whole room. The bright line made public. |",
    "| 7:05–7:15 | Block 4: The three rules read aloud | Movement 2 | Lead Comp + cohort | Verbatim, to the whole room. The bright line made public. |")
sub("| 7:15–7:25 | Block 5: The covering named | Movement 3 | Each senior | Each new FC1 names their adult aloud. Parent + Lead Companion sign-off confirmed publicly. |",
    "| 7:15–7:25 | Block 5: The covering named | Movement 3 | The covering + each member | The church's covering takes authority publicly; each Companion names their own covering aloud. |")
sub("| 7:25–7:45 | Block 6: The commissioning | Movement 4 | Team, parents, cohort | Specific witnessed blessing over each FC1; the charge; the cohort speaks the Aaronic over them. |",
    "| 7:25–7:45 | Block 6: The commissioning | Movement 4 | The covering, the room | Specific witnessed blessing over each Companion; the charge; the room speaks the Aaronic over them. |")
sub("| 7:45–7:50 | Block 7: The first Lab scheduled | Movement 4 | Lead Comp | The date announced aloud, held up, written down. The exit is an entrance. |",
    "| 7:45–7:50 | Block 7: The family year dated | Movement 4 | Lead Comp | The date announced aloud, held up, written down. The exit is an entrance. |")
sub("| 7:50–8:00 | Block 8: The final rep — the container closed | Movement 1 | A senior | A senior closes from memory. Sending. End. |",
    "| 7:50–8:00 | Block 8: The final rep — the container closed | Movement 1 | A member | A member closes from memory. Sending. End. |")

if fail == 0:
    io.open(f, 'w', encoding='utf-8').write(s)
print(f'W15 part 2: done, {fail} failures')
sys.exit(1 if fail else 0)
